api_platform:
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' ]
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    swagger:
        versions: [ 3 ]
        # Options par default
    collection:
        pagination:
            enabled: false
            items_per_page: 5
            client_enabled: true #permet de rajouter l'option de page dans la barre d'adresse pour activer ou desactiver la pagination
            client_items_per_page: true #permet au client de choisir le nombre d'element par page en le precisant dans la barre d'adresse
            enabled_parameter_name: 'pagination' #modifie le nom du parametre a entrer dans la barre d'adresse pour l'enabled par default (pagination=true) maintenant (paginator=true)
            items_per_page_parameter_name: 'count' #Modifie le nom du parametre (itemsPerPage par ipp)
